### ISSUE TITLE
Question – calendar events, recurring (or not) ?

### ISSUE THREAD

**Issue by straup** [sgillies/geojson-events#4]
Like something you might otherwise encode in vCal. Do these sorts of events fit the model you are imagining? The examples so far suggest that they wouldn't necessarily be suitable for recurring calendar events but maybe it's just early days?

Is there, or will there be, a fixed list of `when.type` descriptors or is that sort of thing left up to individual applications and consensus?

Any feelings about the LoC's ExtendedDateTime Format work and its applicability?

**Comment by sgillies** [comment]
@straup I haven't considered recurring events at all. I would like this extension to be useful in planning, safety, and decision making in general, but not be a full fledged calendar data format. What kind of phenomena manifest at regular intervals and keep their identity as a single feature? 

On the one hand, I'm attracted to https://www.loc.gov/standards/datetime/pre-submission.html because it could allow representation of fuzzy instants and intervals without requiring any new JSON objects or properties, and maybe even make the Instant/Interval objects unecessary (because we can do `"when": "2004-02-01/2005-02-08"`). On the other hand, implementations of its level 2 features are scarce.

I'd be willing to write up a different version of the extension that relied almost entirely on EDTF for all of us to compare.

**Comment by sgillies** [comment]
Passing on recurring events for now.
